# Generated by Django 3.2 on 2021-05-05 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='passcode',
            field=models.CharField(blank=True, editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='key',
            field=models.UUIDField(blank=True, editable=False),
        ),
    ]
