# Generated by Django 3.1.5 on 2021-01-16 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('projects', '0003_auto_20210116_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='teams',
            field=models.ManyToManyField(related_name='project_teams', to='users.Team'),
        ),
    ]
