# Generated by Django 3.1.5 on 2021-02-01 23:11

from django.db import migrations, models
import django.db.models.deletion
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_minitask'),
    ]

    operations = [
        migrations.AddField(
            model_name='minitask',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_mini_task', to='projects.task'),
        ),
        migrations.AlterField(
            model_name='minitask',
            name='id',
            field=hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False),
        ),
    ]
