# Generated by Django 3.2 on 2021-05-06 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_invitation_anyone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='key',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
