# Generated by Django 3.1.5 on 2021-02-01 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20210202_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minitask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mini_tasks', to='projects.task'),
        ),
    ]
