# Generated by Django 3.1.5 on 2021-01-16 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('projects', '0006_auto_20210117_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='project_teams', to='users.Team'),
        ),
    ]
