# Generated by Django 3.1.6 on 2021-02-16 19:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0009_auto_20210210_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned',
        ),
        migrations.AddField(
            model_name='task',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='task_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
