# Generated by Django 3.1.7 on 2021-04-03 11:13

from django.db import migrations, models
import django.db.models.deletion
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20210221_0716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=20, primary_key=True, serialize=False)),
                ('allowed_user', models.JSONField(blank=True, null=True)),
                ('key', models.CharField(blank=True, editable=False, max_length=30, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invitation', to='projects.project')),
            ],
        ),
    ]
