# Generated by Django 3.1.7 on 2021-04-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_remove_invitation_allowed_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
