# Generated by Django 4.0 on 2021-12-29 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210221_0716'),
        ('tasks', '0002_alter_tasklog_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)ss', to='users.user'),
        ),
        migrations.AlterField(
            model_name='task',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)ss', to='users.user'),
        ),
    ]
