# Generated by Django 3.2.2 on 2021-05-20 00:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_tasklog_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='moved_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
