# Generated by Django 4.0 on 2021-12-29 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_subtask_creator_alter_task_creator'),
        ('tasks', '0003_task_moved_at'),
    ]

    operations = [
    ]
