
// request sent
export const GET_USER_PROJECTS = 'GET_USER_PROJECTS'
export const GET_PROJECT = 'GET_PROJECT'
export const GET_BOARDS = 'GET_BOARDS'
export const ADD_TASK = 'ADD_TASK';
export const CREATE_BOARD = 'CREATE_BOARD';
export const GET_TASK = 'GET_TASK'

// request success
export const PROJECTS_LOADED = 'PROJECTS_LOADED'
export const PROJECT_LOADED = 'PROJECT_LOADED'
export const BOARDS_LOADED = 'BOARDS_LOADED'
export const TASK_LOADED = 'TASK_LOADED'
export let TASK_ADDED = 'TASK_ADDED'
export const BOARD_CREATED = 'BOARD_CREATED';
export const BOARD_DELETED = 'BOARD_DELETED';

// request failed
export const PROJECTS_REQUEST_FAILED = 'PROJECTS_REQUEST_FAILED'
export const PROJECT_REQUEST_FAILED = 'PROJECT_REQUEST_FAILED'
export const BOARDS_REQUEST_FAILED = 'BOARDS_REQUEST_FAILED'
export const TASK_REQUEST_FAILED = 'TASK_REQUEST_FAILED'

// clear
export const CLEAR_PROJECT_STATE = 'CLEAR_PROJECT_STATE';
