export const TASKS_LOADED = 'TASKS_LOADED';
// request sent
export const GET_USER_PROJECTS = 'GET_USER_PROJECTS'
export const GET_PROJECT = 'GET_PROJECT'
export const GET_BOARDS = 'GET_BOARDS'
export const ADD_TASK = 'ADD_TASK';
export const CREATE_BOARD = 'CREATE_BOARD';
export const GET_TASK = 'GET_TASK'
export const TASK_VIEW_REQUESTING = 'TASK_VIEW_REQUESTING';

// request success
export const PROJECTS_LOADED = 'PROJECTS_LOADED'
export const PROJECT_LOADED = 'PROJECT_LOADED'
export const TASK_LOADED = 'TASK_LOADED'
export const TASK_ADDED = 'TASK_ADDED'
export const TASK_UPDATED = 'TASK_UPDATED';
export const TASK_MEMBER_ALTERED = 'TASK_MEMBER_ALTERED';
export const TASK_DELETED = 'TASK_DELETED';
export const BOARDS_LOADED = 'BOARDS_LOADED'
export const BOARD_CREATED = 'BOARD_CREATED';
export const BOARD_DELETED = 'BOARD_DELETED';
export const COMMENT_ADDED = 'COMMENT_ADDED';
export const COMMENT_DELETED = 'COMMENT_DELETED';

// request failed
export const PROJECTS_REQUEST_FAILED = 'PROJECTS_REQUEST_FAILED'
export const PROJECT_REQUEST_FAILED = 'PROJECT_REQUEST_FAILED'
export const BOARDS_REQUEST_FAILED = 'BOARDS_REQUEST_FAILED'
export const TASK_REQUEST_FAILED = 'TASK_REQUEST_FAILED'
export const COMMENT_REQUEST_FAILED = 'COMMENT_REQUEST_FAILED'

// clear
export const CLEAR_PROJECT_STATE = 'CLEAR_PROJECT_STATE';
export const CLEAR_TASK_STATE = 'CLEAR_TASK_STATE';
export const CLEAR_BOARD_STATE = 'CLEAR_BOARD_STATE';
