export const NEW_ALERT = "NEW_ALERT";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ALERTS = "CLEAR_ALERTS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

// auth types
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_REQUEST_SENT = "AUTH_REQUEST_SENT";
export const AUTH_REQUEST_DONE = "AUTH_REQUEST_DONE";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const EMAIL_VERIFIED = "EMAIL_VERIFIED";
export const EMAIL_VERIFICATION_FAILED = "EMAIL_VERIFICATION_FAILED";
export const RESET_LINK_SENT = "RESET_LINK_SENT";
export const RESET_LINK_SENT_FAILED = "RESET_LINK_SENT_FAILED";
export const PASSWORD_CHANGED = "PASSWORD_CHANGED";
export const PASSWORD_CHANGE_FAILED = "PASSWORD_CHANGE_FAILED";
export const PASSWORD_RESET_FAILED = "PASSWORD_RESET_FAILED";
export const PASSWORD_RESET_SUCCESS = "PASSWORD_RESET_SUCCESS";
